// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUGs7AzRDmjXv0ReCE3BYLQcO29XqcQug',
    appId: '1:843608827725:web:9c122dda418d777e11b904',
    messagingSenderId: '843608827725',
    projectId: 'eduvantage-804c1',
    authDomain: 'eduvantage-804c1.firebaseapp.com',
    storageBucket: 'eduvantage-804c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiifta1liAJZiZb3Ns-rRU9wgXadm-1CU',
    appId: '1:843608827725:android:37a60dfc6aad263711b904',
    messagingSenderId: '843608827725',
    projectId: 'eduvantage-804c1',
    storageBucket: 'eduvantage-804c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMefIBp-dTGUKt7pJao2eNGnB2bGOcqxA',
    appId: '1:843608827725:ios:a620c209c0f02adc11b904',
    messagingSenderId: '843608827725',
    projectId: 'eduvantage-804c1',
    storageBucket: 'eduvantage-804c1.firebasestorage.app',
    iosBundleId: 'com.example.eduvantage',
  );
}
